### ISSUE TITLE
🐛 [Bug Report]: 

### ISSUE THREAD

**Issue by kkkkkkkkkkkkk-ddd** [WoW-CMS/BlizzCMS#106]
### BlizzCMS Version

1.2.1

### Emulator

TrinityCore

### PHP Version

PHP 7.4

### Operating system

Windows

### Web server

Apache

### Database

MySQL 8.0  I think?

### What happened?

Everything works just fine and dandy. 
When accessing from static IP    Can create account, login to account.
When accessing from domain   it wont login nor create account.

AN ERROR WAS ENCOUNTERED
The action you have requested is not allowed.

Sorry if its something dumb.
Cheers for this gem!

### How can the issue be reproduced?

Accessing from static IP & Domain.

**Comment by DZywolf** [comment]
Hello, about your problem, first it is necessary to clarify something:

1. In your issue is established that it is related to version 1.X
2. If you downloaded the latest changes from the main branch, I must clarify that it is version 2.X and it is still in beta.

Finishing the clarification, let's respond to the problem that you have:

Due to a change you made to `$config['base_url']` which you can find in the following path `application/config/config.php`, it is only allowing access depending on what you used.

**Example:**
- If you use IP it will only be accessible through it.
- If you use Domain it will only be accessible through it.
- If the configuration is still the default, the host server will be determined internally if it is IP/Domain, so you can access both.

**As additional information:**
- In version 1.X the base_url by default verifies if the request is for HTTP/HTTPS.
- In version 2.X it can now be installed from a subfolder.

**Comment by kkkkkkkkkkkkk-ddd** [comment]
Hey. 
Thank you so much for taking time & replaying. 

I haven't touch it at all (Config) so it recognize 
" IP/Domain, so you can access both."
Been trying to use beta version as well but given up since something in SQL had to be changed can't remember exactly  so 1.2.1 version installed.

I'm 100% doing something wrong but should I edit something?
was experimenting with adding IP & domain to:

"$config['base_url'] = (is_https() ? 'https://' : 'http://')"

It will just show site as broken or what not. 

Not sure does "SSL" have some problems with it as well.
(Got SSL for IP working correct  not for domain while attempting first time. So kinda given up on it  until other stuff are corrected.)
So unsure does that maybe have some effect as well?

I can feel my brain growing in real time.

Once again thank you so much.

**Comment by DZywolf** [comment]
Maybe you are making a mistake when trying to configure it. I give you some examples for version `1.X` that should work in each case:

```php
// Configuration by IP
$config['base_url'] = $protocol."127.0.0.1/";
```

```php
// Configuration by Domain
$config['base_url'] = $protocol."mywebsite.com/";
```

Default config is:
https://github.com/WoW-CMS/BlizzCMS/blob/c2c01aa81488f8d434b4b4ffa8791b996ecc24f5/application/config/config.php#L26-L27

**Comment by kkkkkkkkkkkkk-ddd** [comment]
@DZywolf  
I see my mistake thank you for explaining.
Been adding link  to wrong section how ever problem persist. 

After adding static IP:   site loads,  login works etc. 
After adding domain:  Site wont load at all.  
(On  IP nor domain)
But this should be obvious since  domain is redirect to IP +Mask.
 However if I disable "Mask" on domain thigs works fine. 

Starting to feel stupid for some days now.

**Comment by DZywolf** [comment]
If you use a **domain** the website will not load due to the fact that its 'base_url' is the domain and it has no way of knowing if that domain is pointing to the **IP** if you don't have an **A Record** (DNS).

**Comment by kkkkkkkkkkkkk-ddd** [comment]
Yes it was "A Record" 
Thank you SO  MUCH!
