### ISSUE TITLE
🐛 [Bug Report]: 

### ISSUE THREAD

**Issue by brunolopes1996** [WoW-CMS/BlizzCMS#126]
### BlizzCMS Version

latest

### Emulator

Other

### PHP Version

PHP 7.4

### Operating system

Windows

### Web server

Apache

### Database

5.5.9

### What happened?

Hello, im trying to install BlizzCMS on emucoach mist of pandaria repack, I have all the requierements i m able to use composer then i start the apache and when i start to fill the tables info and click next it just reloads the webpage and shows "this page is not working"

### How can the issue be reproduced?

downloading the mist of pandaria emucoach repack and trying to install the CMS

### Screenshots

![image](https://github.com/WoW-CMS/BlizzCMS/assets/12574972/7b5c4c71-8d14-482a-845a-b3bf5e306815)

![image](https://github.com/WoW-CMS/BlizzCMS/assets/12574972/ba24a609-6d45-4630-b94f-a3e14d10f30d)

![image](https://github.com/WoW-CMS/BlizzCMS/assets/12574972/2c6491b6-09ff-4369-9a7c-f4af2dc78b9d)

**Comment by sayghteight** [comment]
Hi @brunolopes1996 ,

Unfortunately we cannot reproduce the bug you are reporting in the repack. We only support emulators, repacks are made by third parties and they can modify or alter the order of the account tables.

We advise you to use an emulator and compile that emulator on your machine, since supporting the thousands of repacks that appear every year would be impossible.

Kind regards,

Darthar.
