### ISSUE TITLE
[Suggest]: Much needed features!

### ISSUE THREAD

**Issue by Fot3k** [WoW-CMS/BlizzCMS#30]
### Is your feature request related to a problem? Please describe.

- Can't re-order any post types such as news articles or store items. If you want them in a specific order you have to create them in that order.

- A browser image upload feature is much needed, putting HTML image sources into every description box is very tedious and time-consuming. This is again for news articles and store items. There is one for news thumbnails but not the main content or store items.

- News article summaries on the home page use truncating (mb_substr) but cut off per letter rather than finishing on a word or ending a sentence. A better solution would be to provide a separate input for the summary and another for the main article.

- News article summary thumbnails don't fit their containers when the text exceeds the height. The border stretches but the image does not resize with it.

- The mobile burger menu opens on touch but doesn't close again — you have to tap the oddly placed X to close the menu. Obviously, the best solution is to allow the burger menu to open and close on interaction.

- Some elements and areas aren't responsive, particularly leaderboard and timer tables. They should have a breakpoint on viewport reduction to fit.

### Describe the solution you'd like.

These changes are big QOL features that should be implemented to vastly improve the CMS. Having just created a new theme for BlizzCMS it took much longer than it should have with not having these basic features (in simple terms) There are obviously lots of other features that the CMS would benefit from but I feel these alone would be a massive improvement.

### Additional context.

Appreciate your work on this open-source project, hopefully, more people can jump aboard and improve.

**Comment by Fot3k** [comment]
The store needs an alert that prompts the user to say that their purchase was complete. Currently, the purchase completes without any mention if it was successful or not etc. It just clears your basket.

**Comment by sayghteight** [comment]
Hello @Fot3k 

- Can't re-order any post types such as news articles or store items. If you want them in a specific order you have to create them in that order.

_It is a good idea, we could add an order field so that you can re-order the news, anyway, a news is ordered by the publication date from the most recent to the oldest._

- A browser image upload feature is much needed, putting HTML image sources into every description box is very tedious and time-consuming. This is again for news articles and store items. There is one for news thumbnails but not the main content or store items.

_We could add something like a middle section where all the images are saved, it is something that should be studied._

- News article summaries on the home page use truncating (mb_substr) but cut off per letter rather than finishing on a word or ending a sentence. A better solution would be to provide a separate input for the summary and another for the main article.

_It is something that will be taken into account for possible improvements._

-     The mobile burger menu opens on touch but doesn't close again — you have to tap the oddly placed X to close the menu. Obviously, the best solution is to allow the burger menu to open and close on interaction.

_I understand what you mean, I think the new version is already added._

- Some elements and areas aren't responsive, particularly leaderboard and timer tables. They should have a breakpoint on viewport reduction to fit.

_We have to review many sections, it will take time but it will be made or modified to be responsive._

Work is being done to improve the life cycle of the product, this is something that takes time but many things have been improved in refactor. This, obviously as I said, cannot be applied to Master, but this branch is already allowed to be reviewed, all these changes will be reviewed to apply either in refactor or in master depending on whether the improvement is urgent or not.

Thank you very much, we take your suggestions into account.
